apiVersion: v1
kind: Service
metadata:
 name: app
spec:
 selector:
   role: app
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment
 labels:
   role: app
spec:
 replicas: 2
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: app
       image: "kapilnegi/java-app:2.0"
     - name: web
       image: "kapilnegi/nginx:1.3"
