---
apiVersion: v1
kind: Service
metadata:
  name: springmvcform
spec:
  selector:
    app: springmvcform
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: springmvcform
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: springmvcform
        tier: backend
        track: stable
    spec:
      containers:
        - name: maven
          image: "prakharbhatia4/prakhar:50"
          ports:
            - name: http
              containerPort: 8080
